services:
  api:
    image: ayythakur/mlops-api:latest
    container_name: mlops-api
    ports:
      - "8000:8000"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on: [api]

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on: [prometheus]

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    command: >
      mlflow ui
      --host 0.0.0.0
      --port 5000
      --backend-store-uri /mlruns
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    restart: unless-stopped
