name: CI

on:
  push:
    branches: [ main, development ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt
      - run: pip install -r requirements-dev.txt
      - run: flake8 .
      - run: pytest -q

  docker:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/mlops-api:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE
          docker tag $IMAGE ${{ secrets.DOCKERHUB_USERNAME }}/mlops-api:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlops-api:latest
