name: CI

on:
  push:
    branches: [ main, development ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # Force a portable local MLflow store on CI (avoids Windows path like /F:)
      MLFLOW_TRACKING_URI: file:./mlruns
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt -r requirements-dev.txt
      - name: Lint
        run: python -m flake8 .
      - name: Test
        run: python -m pytest -q

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push (sha + latest)
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/mlops-api:${{ github.sha }}
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
          docker tag "$IMAGE" ${{ secrets.DOCKERHUB_USERNAME }}/mlops-api:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlops-api:latest
